/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Database;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Farhan
 */
public class AddMatch extends javax.swing.JFrame {

    /**
     * Creates new form addmatch
     */
//    Connection con = null;
//    PreparedStatement pst = null;
//    ResultSet rs = null;
//    
    public AddMatch() {
        initComponents();
//        combobox();
        
    }
//    private void combobox(){
//        
//        try {
//            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pbo_fix", "root", "");
//            String sql = "select * from team  ";
//            pst = con.prepareStatement(sql);
//            rs = pst.executeQuery();
//            while(rs.next()){
//                String name = rs.getString("nama");
//                team1.addItem(name);
//                team2.addItem(name);
//                
//            }
//        }catch(Exception e){
//            JOptionPane.showMessageDialog(null, e);
//        }
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        team1 = new javax.swing.JComboBox<>();
        team2 = new javax.swing.JComboBox<>();
        score1 = new javax.swing.JTextField();
        score2 = new javax.swing.JTextField();
        add_data = new javax.swing.JButton();
        table = new javax.swing.JButton();
        home = new javax.swing.JButton();
        notif = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        team1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        getContentPane().add(team1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 270, 40));

        team2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        getContentPane().add(team2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, 270, 40));

        score1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        score1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(score1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 110, 200));

        score2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        score2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(score2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 420, 110, 200));

        add_data.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        add_data.setText("ADD");
        getContentPane().add(add_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 670, 140, 70));

        table.setText("table");
        getContentPane().add(table, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 800, 100, -1));

        home.setText("home");
        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 800, 100, -1));

        notif.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        getContentPane().add(notif, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 750, 240, 19));

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\NetBeansProjects\\IF-42-01_Kelompok-1_AplikasiKlasemenBola\\src\\View\\ADD match.jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 840));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddMatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddMatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddMatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddMatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddMatch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_data;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel notif;
    private javax.swing.JTextField score1;
    private javax.swing.JTextField score2;
    private javax.swing.JButton table;
    private javax.swing.JComboBox<String> team1;
    private javax.swing.JComboBox<String> team2;
    // End of variables declaration//GEN-END:variables

    public JButton getAdd_data() {
        return add_data;
    }

    public JButton getHome() {
        return home;
    }

    public int getScore1() {
        int a = Integer.parseInt(score1.getText());
        return a;

    }

    public int getScore2() {
        int a = Integer.parseInt(score2.getText());
        return a;
    }

    public JComboBox<String> getTeam1() {
        return team1;
    }

    public JComboBox<String> getTeam2() {
        return team2;
    }

    public JButton getTable() {
        return table;
    }

    public JLabel getNotif() {
        return notif;
    }

    public void setNotif(JLabel notif) {
        this.notif = notif;
    }
    
 
    
    public void addActionListener(ActionListener x){
        home.addActionListener(x);
        add_data.addActionListener(x);
        table.addActionListener(x);
    }

}
