/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Farhan
 */
public class AddTeam extends javax.swing.JFrame {

    /**
     * Creates new form addteam
     */
    public AddTeam() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        team_name = new javax.swing.JTextField();
        add_team = new javax.swing.JButton();
        home = new javax.swing.JButton();
        notif = new javax.swing.JLabel();
        WALLPAPER = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(team_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, 390, -1));

        add_team.setText("add");
        getContentPane().add(add_team, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 390, 80, -1));

        home.setText("home");
        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 790, 100, -1));

        notif.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        getContentPane().add(notif, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 400, 16));

        WALLPAPER.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/ADD TEAM.jpg"))); // NOI18N
        getContentPane().add(WALLPAPER, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1800, 850));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddTeam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel WALLPAPER;
    private javax.swing.JButton add_team;
    private javax.swing.JButton home;
    private javax.swing.JLabel notif;
    private javax.swing.JTextField team_name;
    // End of variables declaration//GEN-END:variables

    public JButton getAdd_team() {
        return add_team;
    }

    public String getTeam_name() {
        return team_name.getText();
    }

    public JButton getHome() {
        return home;
    }

    public JLabel getNotif() {
        return notif;
    }

    public void setNotif(JLabel notif) {
        this.notif = notif;
    }

    public void addActionListener(ActionListener x){
        add_team.addActionListener(x);
        home.addActionListener(x);
    }
    
}
