/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.JToggleButton;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sam
 */
public class Welcome extends javax.swing.JFrame {

    /**
     * Creates new form Welcome
     */
    public Welcome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SHOW_TABLE = new javax.swing.JButton();
        ADD_TEAM = new javax.swing.JButton();
        ADD_MATCH = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SHOW_TABLE.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        SHOW_TABLE.setText("SHOW TABLE");
        SHOW_TABLE.setToolTipText("");
        SHOW_TABLE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SHOW_TABLEActionPerformed(evt);
            }
        });
        getContentPane().add(SHOW_TABLE, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 130, 30));

        ADD_TEAM.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ADD_TEAM.setText("ADD TEAM");
        ADD_TEAM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD_TEAMActionPerformed(evt);
            }
        });
        getContentPane().add(ADD_TEAM, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 130, 30));

        ADD_MATCH.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ADD_MATCH.setText("ADD MATCH");
        ADD_MATCH.setToolTipText("");
        ADD_MATCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD_MATCHActionPerformed(evt);
            }
        });
        getContentPane().add(ADD_MATCH, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 130, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/welcome.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SHOW_TABLEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SHOW_TABLEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SHOW_TABLEActionPerformed

    private void ADD_TEAMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD_TEAMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD_TEAMActionPerformed

    private void ADD_MATCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD_MATCHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADD_MATCHActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD_MATCH;
    private javax.swing.JButton ADD_TEAM;
    private javax.swing.JButton SHOW_TABLE;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables


    public JButton getADD_TEAM() {
        return ADD_TEAM;
    }

    public JButton getSHOW_TABLE() {
        return SHOW_TABLE;
    }

    public JButton getADD_MATCH() {
        return ADD_MATCH;
    }
    
    

    
public void addActionListener(ActionListener x){
        ADD_TEAM.addActionListener(x);
        SHOW_TABLE.addActionListener(x);
        ADD_MATCH.addActionListener(x);
    }

}
